//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seating_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_detail
    {
        public event_detail()
        {
            this.guests = new HashSet<guest>();
            this.seats = new HashSet<seat>();
            this.tables = new HashSet<table>();
        }
    
        public int event_id { get; set; }
        public string event_name { get; set; }
        public string event_details { get; set; }
        public System.DateTime date_time_created { get; set; }
        public System.DateTime date_time_updated { get; set; }
    
        public virtual ICollection<guest> guests { get; set; }
        public virtual ICollection<seat> seats { get; set; }
        public virtual ICollection<table> tables { get; set; }
    }
}
