//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seating_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public table()
        {
            this.seats = new HashSet<seat>();
        }
    
        public int table_id { get; set; }
        public string table_name { get; set; }
        public int event_id { get; set; }
    
        public virtual ICollection<seat> seats { get; set; }
        public virtual event_details event_details { get; set; }
    }
}
