//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seating_Planner.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeatingPlannerEntityDataModelContainer : DbContext
    {
        public SeatingPlannerEntityDataModelContainer()
            : base("name=SeatingPlannerEntityDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<guest> guests { get; set; }
        public DbSet<table> tables { get; set; }
        public DbSet<seat> seats { get; set; }
        public DbSet<event_details> event_details { get; set; }
    }
}
